[assembly: System.Reflection.AssemblyVersion("1.4.0.0")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Hexasystems Inc. 2010")]
[assembly: System.Reflection.AssemblyCompany("Hexasystems Inc.")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]