[assembly: System.Reflection.AssemblyVersion("1.3.0.2")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Hexasystems Inc. 2010")]
[assembly: System.Reflection.AssemblyProduct("netDumbster")]
[assembly: System.Reflection.AssemblyCompany("Hexasystems Inc.")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyTitle("netDumbster")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]

